// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/resend.ts";
import * as $$$$$$$$$$$1 from "./apps/decohub.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Carousel.tsx";
import * as $$$$$$1 from "./sections/Component.tsx";
import * as $$$$$$2 from "./sections/ContactForm.tsx";
import * as $$$$$$3 from "./sections/CookieConsent.tsx";
import * as $$$$$$4 from "./sections/CtaBanner.tsx";
import * as $$$$$$5 from "./sections/DescriptiveBanner.tsx";
import * as $$$$$$6 from "./sections/ExtensiveText.tsx";
import * as $$$$$$7 from "./sections/Footer.tsx";
import * as $$$$$$8 from "./sections/Gallery.tsx";
import * as $$$$$$9 from "./sections/Header.tsx";
import * as $$$$$$10 from "./sections/Hero.tsx";
import * as $$$$$$11 from "./sections/HeroVideo.tsx";
import * as $$$$$$12 from "./sections/IconTileList.tsx";
import * as $$$$$$13 from "./sections/ImageShelf.tsx";
import * as $$$$$$14 from "./sections/ImageWithParagraph.tsx";
import * as $$$$$$15 from "./sections/LabelText.tsx";
import * as $$$$$$16 from "./sections/Map.tsx";
import * as $$$$$$17 from "./sections/Testimonials.tsx";
import * as $$$$$$18 from "./sections/TextBlock.tsx";
import * as $$$$$$19 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Carousel.tsx": $$$$$$0,
    "site/sections/Component.tsx": $$$$$$1,
    "site/sections/ContactForm.tsx": $$$$$$2,
    "site/sections/CookieConsent.tsx": $$$$$$3,
    "site/sections/CtaBanner.tsx": $$$$$$4,
    "site/sections/DescriptiveBanner.tsx": $$$$$$5,
    "site/sections/ExtensiveText.tsx": $$$$$$6,
    "site/sections/Footer.tsx": $$$$$$7,
    "site/sections/Gallery.tsx": $$$$$$8,
    "site/sections/Header.tsx": $$$$$$9,
    "site/sections/Hero.tsx": $$$$$$10,
    "site/sections/HeroVideo.tsx": $$$$$$11,
    "site/sections/IconTileList.tsx": $$$$$$12,
    "site/sections/ImageShelf.tsx": $$$$$$13,
    "site/sections/ImageWithParagraph.tsx": $$$$$$14,
    "site/sections/LabelText.tsx": $$$$$$15,
    "site/sections/Map.tsx": $$$$$$16,
    "site/sections/Testimonials.tsx": $$$$$$17,
    "site/sections/TextBlock.tsx": $$$$$$18,
    "site/sections/Theme/Theme.tsx": $$$$$$19,
  },
  "apps": {
    "site/apps/deco/resend.ts": $$$$$$$$$$$0,
    "site/apps/decohub.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
